package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

filegroup(
    name = "testdata",
    srcs = glob(["testdata/*.json"]),
)
