# Structure Definitions for the Us-Core profiles.

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

# These files contain us core descriptors.
filegroup(
    name = "descriptors",
    srcs = glob(["*.descriptor.prototxt"]),
)
