package(
    default_applicable_licenses = [""],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files(
    [
        "*.bzl",
        "cython.BUILD",
        "dependencies.bzl",
        "go_dependencies.bzl",
        "requirements.txt",
    ],
)
