package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(
    [
        "*.bzl",
        "cython.BUILD",
        "requirements.txt",
        "dependencies.bzl",
    ],
)
