//    Copyright 2020 Google Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        https://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: go/jsonformat/internal/accessor/accessor_test.proto

package accessor_test_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StringList is a merely a list of strings which is supposed to be used only in
// proto accessor test.
type StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of strings
	Strings []string `protobuf:"bytes,1,rep,name=strings" json:"strings,omitempty"`
}

func (x *StringList) Reset() {
	*x = StringList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_jsonformat_internal_accessor_accessor_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_go_jsonformat_internal_accessor_accessor_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescGZIP(), []int{0}
}

func (x *StringList) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

var File_go_jsonformat_internal_accessor_accessor_test_proto protoreflect.FileDescriptor

var file_go_jsonformat_internal_accessor_accessor_test_proto_rawDesc = []byte{
	0x0a, 0x33, 0x67, 0x6f, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x66, 0x68, 0x69, 0x72, 0x2e, 0x67, 0x6f, 0x2e, 0x6a,
	0x73, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x0a, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x73, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x66, 0x68, 0x69, 0x72, 0x2f, 0x67, 0x6f,
	0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x6f, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescOnce sync.Once
	file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescData = file_go_jsonformat_internal_accessor_accessor_test_proto_rawDesc
)

func file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescGZIP() []byte {
	file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescOnce.Do(func() {
		file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescData)
	})
	return file_go_jsonformat_internal_accessor_accessor_test_proto_rawDescData
}

var file_go_jsonformat_internal_accessor_accessor_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_go_jsonformat_internal_accessor_accessor_test_proto_goTypes = []interface{}{
	(*StringList)(nil), // 0: fhir.go.jsonformat.internal.accessor.StringList
}
var file_go_jsonformat_internal_accessor_accessor_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_jsonformat_internal_accessor_accessor_test_proto_init() }
func file_go_jsonformat_internal_accessor_accessor_test_proto_init() {
	if File_go_jsonformat_internal_accessor_accessor_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_jsonformat_internal_accessor_accessor_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_jsonformat_internal_accessor_accessor_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_jsonformat_internal_accessor_accessor_test_proto_goTypes,
		DependencyIndexes: file_go_jsonformat_internal_accessor_accessor_test_proto_depIdxs,
		MessageInfos:      file_go_jsonformat_internal_accessor_accessor_test_proto_msgTypes,
	}.Build()
	File_go_jsonformat_internal_accessor_accessor_test_proto = out.File
	file_go_jsonformat_internal_accessor_accessor_test_proto_rawDesc = nil
	file_go_jsonformat_internal_accessor_accessor_test_proto_goTypes = nil
	file_go_jsonformat_internal_accessor_accessor_test_proto_depIdxs = nil
}
