resource_config {
  key: "Claim"
  value {
    default_timestamp_fields: "Claim.created"
    default_timestamp_fields: "Claim.billablePeriod.end"
  }
}
resource_config {
  key: "Composition"
  value {
    default_timestamp_fields: "Composition.date"
    timestamp_override {
      timestamp_field: "Composition.attester[].time"
      resource_field: "Composition.attester[]"
    }
  }
}
resource_config {
  key: "Condition"
  value {
    default_timestamp_fields: "Condition.assertedDate"
  }
}
resource_config {
  key: "Encounter"
  value {
    default_timestamp_fields: "Encounter.period.start"
    timestamp_override {
      timestamp_field: "Encounter.period.end"
      resource_field: "Encounter.length"
      resource_field: "Encounter.period.end"
      resource_field: "Encounter.reason"
      resource_field: "Encounter.diagnosis"
      resource_field: "Encounter.hospitalization.dischargeDisposition"
      resource_field: "Encounter.hospitalization.destination"
      # Encounter.service_provider is medical service.
      resource_field: "Encounter.serviceProvider"
      # Encounter.location is list of rooms.
      # TODO point Encounter.location[] to Encounter.location[].start
      resource_field: "Encounter.location"
    }
  }
}
resource_config {
  key: "MedicationAdministration"
  value {
    default_timestamp_fields: "MedicationAdministration.effective.dateTime"
    default_timestamp_fields: "MedicationAdministration.effective.period.start"
  }
}
resource_config {
  key: "MedicationRequest"
  value {
    default_timestamp_fields: "MedicationRequest.authoredOn"
  }
}
resource_config {
  key: "Observation"
  value {
    default_timestamp_fields: "Observation.effective.dateTime"
  }
}
resource_config {
  key: "Procedure"
  value {
    default_timestamp_fields: "Procedure.performed.dateTime"
    default_timestamp_fields: "Procedure.performed.period.start"
  }
}
resource_config {
  key: "ProcedureRequest"
  value {
    default_timestamp_fields: "ProcedureRequest.authoredOn"
  }
}
