//    Copyright 2022 Google Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        https://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: proto/google/fhir/proto/fhirpath_replacement_list.proto

package fhirpath_replacement_list_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines a list of fhir path expressions to be replaced.
type FHIRPathReplacementList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replacement []*Replacement `protobuf:"bytes,1,rep,name=replacement,proto3" json:"replacement,omitempty"`
}

func (x *FHIRPathReplacementList) Reset() {
	*x = FHIRPathReplacementList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FHIRPathReplacementList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FHIRPathReplacementList) ProtoMessage() {}

func (x *FHIRPathReplacementList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FHIRPathReplacementList.ProtoReflect.Descriptor instead.
func (*FHIRPathReplacementList) Descriptor() ([]byte, []int) {
	return file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescGZIP(), []int{0}
}

func (x *FHIRPathReplacementList) GetReplacement() []*Replacement {
	if x != nil {
		return x.Replacement
	}
	return nil
}

// Defines all the information needed to replace a FHIR Path expression during
// FHIRPath to SQL encoding.
type Replacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The full path from the parent resource to the field containing the
	// expression to be replaced.
	// E.g., if Patient has a subfield meta and meta has a field id, this could be
	// `Patient.meta.id`.
	// If not specified, this will apply to all expressions matching
	// `expression_to_replace`, regardless of element.
	ElementPath string `protobuf:"bytes,1,opt,name=element_path,json=elementPath,proto3" json:"element_path,omitempty"`
	// The expression to be replaced.
	ExpressionToReplace string `protobuf:"bytes,2,opt,name=expression_to_replace,json=expressionToReplace,proto3" json:"expression_to_replace,omitempty"`
	// The expression to be replaced with.
	// TODO(b/221470795): Look into adding a special token (like `$`) that
	// will be replaced with the name of the current resource.
	ReplacementExpression string `protobuf:"bytes,3,opt,name=replacement_expression,json=replacementExpression,proto3" json:"replacement_expression,omitempty"`
}

func (x *Replacement) Reset() {
	*x = Replacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replacement) ProtoMessage() {}

func (x *Replacement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replacement.ProtoReflect.Descriptor instead.
func (*Replacement) Descriptor() ([]byte, []int) {
	return file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescGZIP(), []int{1}
}

func (x *Replacement) GetElementPath() string {
	if x != nil {
		return x.ElementPath
	}
	return ""
}

func (x *Replacement) GetExpressionToReplace() string {
	if x != nil {
		return x.ExpressionToReplace
	}
	return ""
}

func (x *Replacement) GetReplacementExpression() string {
	if x != nil {
		return x.ReplacementExpression
	}
	return ""
}

var File_proto_google_fhir_proto_fhirpath_replacement_list_proto protoreflect.FileDescriptor

var file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDesc = []byte{
	0x0a, 0x37, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x66,
	0x68, 0x69, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x68, 0x69, 0x72, 0x70, 0x61,
	0x74, 0x68, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x66, 0x68, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x17,
	0x46, 0x48, 0x49, 0x52, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x66, 0x68, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x72, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x0b, 0x52, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x32, 0x0a, 0x15,
	0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x5f, 0x72, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x12, 0x35, 0x0a, 0x16, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x15, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x66, 0x68, 0x69,
	0x72, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x66, 0x68, 0x69, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x68, 0x69,
	0x72, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescOnce sync.Once
	file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescData = file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDesc
)

func file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescGZIP() []byte {
	file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescOnce.Do(func() {
		file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescData)
	})
	return file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDescData
}

var file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_google_fhir_proto_fhirpath_replacement_list_proto_goTypes = []interface{}{
	(*FHIRPathReplacementList)(nil), // 0: google.fhir.proto.FHIRPathReplacementList
	(*Replacement)(nil),             // 1: google.fhir.proto.Replacement
}
var file_proto_google_fhir_proto_fhirpath_replacement_list_proto_depIdxs = []int32{
	1, // 0: google.fhir.proto.FHIRPathReplacementList.replacement:type_name -> google.fhir.proto.Replacement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_google_fhir_proto_fhirpath_replacement_list_proto_init() }
func file_proto_google_fhir_proto_fhirpath_replacement_list_proto_init() {
	if File_proto_google_fhir_proto_fhirpath_replacement_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FHIRPathReplacementList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_google_fhir_proto_fhirpath_replacement_list_proto_goTypes,
		DependencyIndexes: file_proto_google_fhir_proto_fhirpath_replacement_list_proto_depIdxs,
		MessageInfos:      file_proto_google_fhir_proto_fhirpath_replacement_list_proto_msgTypes,
	}.Build()
	File_proto_google_fhir_proto_fhirpath_replacement_list_proto = out.File
	file_proto_google_fhir_proto_fhirpath_replacement_list_proto_rawDesc = nil
	file_proto_google_fhir_proto_fhirpath_replacement_list_proto_goTypes = nil
	file_proto_google_fhir_proto_fhirpath_replacement_list_proto_depIdxs = nil
}
