package(
    default_visibility = ["//:__subpackages__"],
)

licenses(["notice"])

filegroup(
    name = "jsonformat",
    srcs = [
        "observation_invalid_unicode.prototxt",
        "observation_three_digit_year.json",
        "observation_three_digit_year.prototxt",
    ],
)
