licenses(["notice"])

# Build files for external dependencies that do not provide build files.

exports_files([
    "libarchive_config.h",
    "libzip_config.h",
    "zipconf.h",
    "zip_err_str.c",
] + glob(["*.BUILD"]))
