licenses(["notice"])
package(default_visibility = ["//visibility:public"],)

py_library(
    name = "protobuf_compare",
    srcs = ["protobuf_compare.py"],
    deps = [
        "@protobuf_archive//:protobuf_python",
        "@six_archive//:six",
    ],
)
