licenses(["notice"])

package(default_visibility = ["//visibility:public"],)

py_library(
    name = "protobuf_compare",
    srcs = ["protobuf_compare.py"],
    deps = [
        "@com_google_protobuf//:protobuf_python",
        "@six_archive//:six",
    ],
)
