# Testdata for the parsers

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

# These files are prototxt representations of sample resources provided by FHIR.
filegroup(
    name = "examples",
    srcs = glob([
        "examples/*.prototxt",
    ]),
)
