licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "terminology_resolver",
    hdrs = ["terminology_resolver.h"],
    strip_include_prefix = "//cc/",
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status:statusor",
    ],
)
