load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

go_library(
    name = "fhirversion",
    srcs = ["fhirversion.go"],
    importpath = "github.com/google/fhir/go/fhirversion",
)
