licenses(["notice"])

package(
    default_applicable_licenses = [""],
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "testdata",
    srcs = glob([
        "*.prototxt",
    ]),
)
