# Testdata for the primitive parsing/printing

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//:__subpackages__"],
)

licenses(["notice"])

filegroup(
    name = "primitives",
    srcs = glob(["*.prototxt"]),
)
