load("//bazel:proto.bzl", "fhir_proto_library")

package(
    default_visibility = ["//:__subpackages__"],
)

licenses(["notice"])

fhir_proto_library(
    srcs = ["generic_proto.proto"],
    proto_library_prefix = "generic_proto",
)
